my:
  datasource:
    ds1:
      host: localhost
      port: 3306
      database: ltts_order
      username: root
      password: 123456
    ds2:
      host: localhost
      port: 3306
      database: ltts_order
      username: root
      password: 123456

 # password: mpw:JCzzOub0Nn4i7HqnoMKLMw==
#  password: ENC(P/+zqfN3nf+ogQoYW/nl/UEitdT7xLgidS1Ik0uNOok=)

mpw:
  key: 8135631e8f67493a

jasypt:
  password: q1w2e3r4t5y6u7=!@345


ltts:
  log:
    enabled: true
    handleType: orderLogHandler
    clusterName: log-center
    serverUrl: http://localhost:9090/log/collect

nacos:
  server-addr: localhost:8848
  namespaces: cf7cb9cd-9740-4b33-b4eb-396f398dde82
  group: LTTS_GROUP