swagger:
  enabled: true
  basePackage: com.lming.ltts.order.controller
  title: Ltts Order Restful API
  description: order server api
  version: 1.0.0
  host: localhost
  contact:
    name: liangming.zhang
    email: liangming.zhang@thermofisher.com
    url: --

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ltts_order?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.lming.ltts.order.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0