swagger:
  enabled: true
  basePackage: com.lming.ltts.auth.controller
  title: Ltts Auth Restful API
  description: Auth server api
  version: 1.0.0
  host: localhost
  contact:
    name: liangming.zhang
    email: liangming.zhang@thermofisher.com
    url: --

# single datasource
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    username: ${mysql.username}
#    password: ${mysql.password}
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 50
#      connection-test-query: SELECT 1
#      max-lifetime: 1800000
#      connection-timeout: 30000

spring:
#  main:
#    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
  application:
    name: ltts-auth-server
